// Copyright (c) 2010-2021 The Open-Transactions developers
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

#include "0_stdafx.hpp"                  // IWYU pragma: associated
#include "1_Internal.hpp"                // IWYU pragma: associated
#include "internal/contact/Contact.hpp"  // IWYU pragma: associated

#include <robin_hood.h>

#include "opentxs/contact/Attribute.hpp"
#include "opentxs/contact/ClaimType.hpp"
#include "opentxs/contact/SectionType.hpp"
#include "opentxs/contact/Types.hpp"
#include "opentxs/core/UnitType.hpp"
#include "serialization/protobuf/ContactEnums.pb.h"
#include "util/Container.hpp"

namespace opentxs::contact
{
using AttributeMap = robin_hood::
    unordered_flat_map<contact::Attribute, proto::ContactItemAttribute>;
using AttributeReverseMap = robin_hood::
    unordered_flat_map<proto::ContactItemAttribute, contact::Attribute>;
using ClaimTypeMap =
    robin_hood::unordered_flat_map<contact::ClaimType, proto::ContactItemType>;
using ClaimTypeReverseMap =
    robin_hood::unordered_flat_map<proto::ContactItemType, contact::ClaimType>;
using SectionTypeMap = robin_hood::
    unordered_flat_map<contact::SectionType, proto::ContactSectionName>;
using SectionTypeReverseMap = robin_hood::
    unordered_flat_map<proto::ContactSectionName, contact::SectionType>;
using UnitTypeMap =
    robin_hood::unordered_flat_map<core::UnitType, contact::ClaimType>;
using UnitTypeReverseMap =
    robin_hood::unordered_flat_map<contact::ClaimType, core::UnitType>;

auto attribute_map() noexcept -> const AttributeMap&;
auto claimtype_map() noexcept -> const ClaimTypeMap&;
auto sectiontype_map() noexcept -> const SectionTypeMap&;
auto unittype_map() noexcept -> const UnitTypeMap&;
}  // namespace opentxs::contact

namespace opentxs::contact
{
auto attribute_map() noexcept -> const AttributeMap&
{
    static const auto map = AttributeMap{
        {Attribute::Error, proto::CITEMATTR_ERROR},
        {Attribute::Active, proto::CITEMATTR_ACTIVE},
        {Attribute::Primary, proto::CITEMATTR_PRIMARY},
        {Attribute::Local, proto::CITEMATTR_LOCAL},
    };

    return map;
}

auto claimtype_map() noexcept -> const ClaimTypeMap&
{
    static const auto map = ClaimTypeMap{
        {ClaimType::Error, proto::CITEMTYPE_ERROR},
        {ClaimType::Individual, proto::CITEMTYPE_INDIVIDUAL},
        {ClaimType::Organization, proto::CITEMTYPE_ORGANIZATION},
        {ClaimType::Business, proto::CITEMTYPE_BUSINESS},
        {ClaimType::Government, proto::CITEMTYPE_GOVERNMENT},
        {ClaimType::Server, proto::CITEMTYPE_SERVER},
        {ClaimType::Prefix, proto::CITEMTYPE_PREFIX},
        {ClaimType::Forename, proto::CITEMTYPE_FORENAME},
        {ClaimType::Middlename, proto::CITEMTYPE_MIDDLENAME},
        {ClaimType::Surname, proto::CITEMTYPE_SURNAME},
        {ClaimType::Pedigree, proto::CITEMTYPE_PEDIGREE},
        {ClaimType::Suffix, proto::CITEMTYPE_SUFFIX},
        {ClaimType::Nickname, proto::CITEMTYPE_NICKNAME},
        {ClaimType::Commonname, proto::CITEMTYPE_COMMONNAME},
        {ClaimType::Passport, proto::CITEMTYPE_PASSPORT},
        {ClaimType::National, proto::CITEMTYPE_NATIONAL},
        {ClaimType::Provincial, proto::CITEMTYPE_PROVINCIAL},
        {ClaimType::Military, proto::CITEMTYPE_MILITARY},
        {ClaimType::PGP, proto::CITEMTYPE_PGP},
        {ClaimType::OTR, proto::CITEMTYPE_OTR},
        {ClaimType::SSL, proto::CITEMTYPE_SSL},
        {ClaimType::Physical, proto::CITEMTYPE_PHYSICAL},
        {ClaimType::Official, proto::CITEMTYPE_OFFICIAL},
        {ClaimType::Birthplace, proto::CITEMTYPE_BIRTHPLACE},
        {ClaimType::Home, proto::CITEMTYPE_HOME},
        {ClaimType::Website, proto::CITEMTYPE_WEBSITE},
        {ClaimType::Opentxs, proto::CITEMTYPE_OPENTXS},
        {ClaimType::Phone, proto::CITEMTYPE_PHONE},
        {ClaimType::Email, proto::CITEMTYPE_EMAIL},
        {ClaimType::Skype, proto::CITEMTYPE_SKYPE},
        {ClaimType::Wire, proto::CITEMTYPE_WIRE},
        {ClaimType::QQ, proto::CITEMTYPE_QQ},
        {ClaimType::Bitmessage, proto::CITEMTYPE_BITMESSAGE},
        {ClaimType::Whatsapp, proto::CITEMTYPE_WHATSAPP},
        {ClaimType::Telegram, proto::CITEMTYPE_TELEGRAM},
        {ClaimType::KIK, proto::CITEMTYPE_KIK},
        {ClaimType::BBM, proto::CITEMTYPE_BBM},
        {ClaimType::Wechat, proto::CITEMTYPE_WECHAT},
        {ClaimType::Kakaotalk, proto::CITEMTYPE_KAKAOTALK},
        {ClaimType::Facebook, proto::CITEMTYPE_FACEBOOK},
        {ClaimType::Google, proto::CITEMTYPE_GOOGLE},
        {ClaimType::Linkedin, proto::CITEMTYPE_LINKEDIN},
        {ClaimType::VK, proto::CITEMTYPE_VK},
        {ClaimType::Aboutme, proto::CITEMTYPE_ABOUTME},
        {ClaimType::Onename, proto::CITEMTYPE_ONENAME},
        {ClaimType::Twitter, proto::CITEMTYPE_TWITTER},
        {ClaimType::Medium, proto::CITEMTYPE_MEDIUM},
        {ClaimType::Tumblr, proto::CITEMTYPE_TUMBLR},
        {ClaimType::Yahoo, proto::CITEMTYPE_YAHOO},
        {ClaimType::Myspace, proto::CITEMTYPE_MYSPACE},
        {ClaimType::Meetup, proto::CITEMTYPE_MEETUP},
        {ClaimType::Reddit, proto::CITEMTYPE_REDDIT},
        {ClaimType::Hackernews, proto::CITEMTYPE_HACKERNEWS},
        {ClaimType::Wikipedia, proto::CITEMTYPE_WIKIPEDIA},
        {ClaimType::Angellist, proto::CITEMTYPE_ANGELLIST},
        {ClaimType::Github, proto::CITEMTYPE_GITHUB},
        {ClaimType::Bitbucket, proto::CITEMTYPE_BITBUCKET},
        {ClaimType::Youtube, proto::CITEMTYPE_YOUTUBE},
        {ClaimType::Vimeo, proto::CITEMTYPE_VIMEO},
        {ClaimType::Twitch, proto::CITEMTYPE_TWITCH},
        {ClaimType::Snapchat, proto::CITEMTYPE_SNAPCHAT},
        {ClaimType::Vine, proto::CITEMTYPE_VINE},
        {ClaimType::Instagram, proto::CITEMTYPE_INSTAGRAM},
        {ClaimType::Pinterest, proto::CITEMTYPE_PINTEREST},
        {ClaimType::Imgur, proto::CITEMTYPE_IMGUR},
        {ClaimType::Flickr, proto::CITEMTYPE_FLICKR},
        {ClaimType::Dribble, proto::CITEMTYPE_DRIBBLE},
        {ClaimType::Behance, proto::CITEMTYPE_BEHANCE},
        {ClaimType::Deviantart, proto::CITEMTYPE_DEVIANTART},
        {ClaimType::Spotify, proto::CITEMTYPE_SPOTIFY},
        {ClaimType::Itunes, proto::CITEMTYPE_ITUNES},
        {ClaimType::Soundcloud, proto::CITEMTYPE_SOUNDCLOUD},
        {ClaimType::Askfm, proto::CITEMTYPE_ASKFM},
        {ClaimType::Ebay, proto::CITEMTYPE_EBAY},
        {ClaimType::Etsy, proto::CITEMTYPE_ETSY},
        {ClaimType::Openbazaar, proto::CITEMTYPE_OPENBAZAAR},
        {ClaimType::Xboxlive, proto::CITEMTYPE_XBOXLIVE},
        {ClaimType::Playstation, proto::CITEMTYPE_PLAYSTATION},
        {ClaimType::Secondlife, proto::CITEMTYPE_SECONDLIFE},
        {ClaimType::Warcraft, proto::CITEMTYPE_WARCRAFT},
        {ClaimType::Alias, proto::CITEMTYPE_ALIAS},
        {ClaimType::Acquaintance, proto::CITEMTYPE_ACQUAINTANCE},
        {ClaimType::Friend, proto::CITEMTYPE_FRIEND},
        {ClaimType::Spouse, proto::CITEMTYPE_SPOUSE},
        {ClaimType::Sibling, proto::CITEMTYPE_SIBLING},
        {ClaimType::Member, proto::CITEMTYPE_MEMBER},
        {ClaimType::Colleague, proto::CITEMTYPE_COLLEAGUE},
        {ClaimType::Parent, proto::CITEMTYPE_PARENT},
        {ClaimType::Child, proto::CITEMTYPE_CHILD},
        {ClaimType::Employer, proto::CITEMTYPE_EMPLOYER},
        {ClaimType::Employee, proto::CITEMTYPE_EMPLOYEE},
        {ClaimType::Citizen, proto::CITEMTYPE_CITIZEN},
        {ClaimType::Photo, proto::CITEMTYPE_PHOTO},
        {ClaimType::Gender, proto::CITEMTYPE_GENDER},
        {ClaimType::Height, proto::CITEMTYPE_HEIGHT},
        {ClaimType::Weight, proto::CITEMTYPE_WEIGHT},
        {ClaimType::Hair, proto::CITEMTYPE_HAIR},
        {ClaimType::Eye, proto::CITEMTYPE_EYE},
        {ClaimType::Skin, proto::CITEMTYPE_SKIN},
        {ClaimType::Ethnicity, proto::CITEMTYPE_ETHNICITY},
        {ClaimType::Language, proto::CITEMTYPE_LANGUAGE},
        {ClaimType::Degree, proto::CITEMTYPE_DEGREE},
        {ClaimType::Certification, proto::CITEMTYPE_CERTIFICATION},
        {ClaimType::Title, proto::CITEMTYPE_TITLE},
        {ClaimType::Skill, proto::CITEMTYPE_SKILL},
        {ClaimType::Award, proto::CITEMTYPE_AWARD},
        {ClaimType::Likes, proto::CITEMTYPE_LIKES},
        {ClaimType::Sexual, proto::CITEMTYPE_SEXUAL},
        {ClaimType::Political, proto::CITEMTYPE_POLITICAL},
        {ClaimType::Religious, proto::CITEMTYPE_RELIGIOUS},
        {ClaimType::Birth, proto::CITEMTYPE_BIRTH},
        {ClaimType::Secondarygraduation, proto::CITEMTYPE_SECONDARYGRADUATION},
        {ClaimType::Universitygraduation,
         proto::CITEMTYPE_UNIVERSITYGRADUATION},
        {ClaimType::Wedding, proto::CITEMTYPE_WEDDING},
        {ClaimType::Accomplishment, proto::CITEMTYPE_ACCOMPLISHMENT},
        {ClaimType::BTC, proto::CITEMTYPE_BTC},
        {ClaimType::ETH, proto::CITEMTYPE_ETH},
        {ClaimType::XRP, proto::CITEMTYPE_XRP},
        {ClaimType::LTC, proto::CITEMTYPE_LTC},
        {ClaimType::DAO, proto::CITEMTYPE_DAO},
        {ClaimType::XEM, proto::CITEMTYPE_XEM},
        {ClaimType::DASH, proto::CITEMTYPE_DASH},
        {ClaimType::MAID, proto::CITEMTYPE_MAID},
        {ClaimType::LSK, proto::CITEMTYPE_LSK},
        {ClaimType::DOGE, proto::CITEMTYPE_DOGE},
        {ClaimType::DGD, proto::CITEMTYPE_DGD},
        {ClaimType::XMR, proto::CITEMTYPE_XMR},
        {ClaimType::WAVES, proto::CITEMTYPE_WAVES},
        {ClaimType::NXT, proto::CITEMTYPE_NXT},
        {ClaimType::SC, proto::CITEMTYPE_SC},
        {ClaimType::STEEM, proto::CITEMTYPE_STEEM},
        {ClaimType::AMP, proto::CITEMTYPE_AMP},
        {ClaimType::XLM, proto::CITEMTYPE_XLM},
        {ClaimType::FCT, proto::CITEMTYPE_FCT},
        {ClaimType::BTS, proto::CITEMTYPE_BTS},
        {ClaimType::USD, proto::CITEMTYPE_USD},
        {ClaimType::EUR, proto::CITEMTYPE_EUR},
        {ClaimType::GBP, proto::CITEMTYPE_GBP},
        {ClaimType::INR, proto::CITEMTYPE_INR},
        {ClaimType::AUD, proto::CITEMTYPE_AUD},
        {ClaimType::CAD, proto::CITEMTYPE_CAD},
        {ClaimType::SGD, proto::CITEMTYPE_SGD},
        {ClaimType::CHF, proto::CITEMTYPE_CHF},
        {ClaimType::MYR, proto::CITEMTYPE_MYR},
        {ClaimType::JPY, proto::CITEMTYPE_JPY},
        {ClaimType::CNY, proto::CITEMTYPE_CNY},
        {ClaimType::NZD, proto::CITEMTYPE_NZD},
        {ClaimType::THB, proto::CITEMTYPE_THB},
        {ClaimType::HUF, proto::CITEMTYPE_HUF},
        {ClaimType::AED, proto::CITEMTYPE_AED},
        {ClaimType::HKD, proto::CITEMTYPE_HKD},
        {ClaimType::MXN, proto::CITEMTYPE_MXN},
        {ClaimType::ZAR, proto::CITEMTYPE_ZAR},
        {ClaimType::PHP, proto::CITEMTYPE_PHP},
        {ClaimType::SEK, proto::CITEMTYPE_SEK},
        {ClaimType::TNBTC, proto::CITEMTYPE_TNBTC},
        {ClaimType::TNXRP, proto::CITEMTYPE_TNXRP},
        {ClaimType::TNLTX, proto::CITEMTYPE_TNLTC},
        {ClaimType::TNXEM, proto::CITEMTYPE_TNXEM},
        {ClaimType::TNDASH, proto::CITEMTYPE_TNDASH},
        {ClaimType::TNMAID, proto::CITEMTYPE_TNMAID},
        {ClaimType::TNLSK, proto::CITEMTYPE_TNLSK},
        {ClaimType::TNDOGE, proto::CITEMTYPE_TNDOGE},
        {ClaimType::TNXMR, proto::CITEMTYPE_TNXMR},
        {ClaimType::TNWAVES, proto::CITEMTYPE_TNWAVES},
        {ClaimType::TNNXT, proto::CITEMTYPE_TNNXT},
        {ClaimType::TNSC, proto::CITEMTYPE_TNSC},
        {ClaimType::TNSTEEM, proto::CITEMTYPE_TNSTEEM},
        {ClaimType::Philosophy, proto::CITEMTYPE_PHILOSOPHY},
        {ClaimType::Met, proto::CITEMTYPE_MET},
        {ClaimType::Fan, proto::CITEMTYPE_FAN},
        {ClaimType::Supervisor, proto::CITEMTYPE_SUPERVISOR},
        {ClaimType::Subordinate, proto::CITEMTYPE_SUBORDINATE},
        {ClaimType::Contact, proto::CITEMTYPE_CONTACT},
        {ClaimType::Refreshed, proto::CITEMTYPE_REFRESHED},
        {ClaimType::BOT, proto::CITEMTYPE_BOT},
        {ClaimType::BCH, proto::CITEMTYPE_BCH},
        {ClaimType::TNBCH, proto::CITEMTYPE_TNBCH},
        {ClaimType::Owner, proto::CITEMTYPE_OWNER},
        {ClaimType::Property, proto::CITEMTYPE_PROPERTY},
        {ClaimType::Unknown, proto::CITEMTYPE_UNKNOWN},
        {ClaimType::Ethereum_Olympic, proto::CITEMTYPE_ETHEREUM_OLYMPIC},
        {ClaimType::Ethereum_Classic, proto::CITEMTYPE_ETHEREUM_CLASSIC},
        {ClaimType::Ethereum_Expanse, proto::CITEMTYPE_ETHEREUM_EXPANSE},
        {ClaimType::Ethereum_Morden, proto::CITEMTYPE_ETHEREUM_MORDEN},
        {ClaimType::Ethereum_Ropsten, proto::CITEMTYPE_ETHEREUM_ROPSTEN},
        {ClaimType::Ethereum_Rinkeby, proto::CITEMTYPE_ETHEREUM_RINKEBY},
        {ClaimType::Ethereum_Kovan, proto::CITEMTYPE_ETHEREUM_KOVAN},
        {ClaimType::Ethereum_Sokol, proto::CITEMTYPE_ETHEREUM_SOKOL},
        {ClaimType::Ethereum_POA, proto::CITEMTYPE_ETHEREUM_POA},
        {ClaimType::PKT, proto::CITEMTYPE_PKT},
        {ClaimType::TNPKT, proto::CITEMTYPE_TNPKT},
        {ClaimType::Regtest, proto::CITEMTYPE_REGTEST},
        {ClaimType::BNB, proto::CITEMTYPE_BNB},
        {ClaimType::SOL, proto::CITEMTYPE_SOL},
        {ClaimType::USDT, proto::CITEMTYPE_USDT},
        {ClaimType::ADA, proto::CITEMTYPE_ADA},
        {ClaimType::DOT, proto::CITEMTYPE_DOT},
        {ClaimType::USDC, proto::CITEMTYPE_USDC},
        {ClaimType::SHIB, proto::CITEMTYPE_SHIB},
        {ClaimType::LUNA, proto::CITEMTYPE_LUNA},
        {ClaimType::AVAX, proto::CITEMTYPE_AVAX},
        {ClaimType::UNI, proto::CITEMTYPE_UNI},
        {ClaimType::LINK, proto::CITEMTYPE_LINK},
        {ClaimType::WBTC, proto::CITEMTYPE_WBTC},
        {ClaimType::BUSD, proto::CITEMTYPE_BUSD},
        {ClaimType::MATIC, proto::CITEMTYPE_MATIC},
        {ClaimType::ALGO, proto::CITEMTYPE_ALGO},
        {ClaimType::VET, proto::CITEMTYPE_VET},
        {ClaimType::AXS, proto::CITEMTYPE_AXS},
        {ClaimType::ICP, proto::CITEMTYPE_ICP},
        {ClaimType::CRO, proto::CITEMTYPE_CRO},
        {ClaimType::ATOM, proto::CITEMTYPE_ATOM},
        {ClaimType::THETA, proto::CITEMTYPE_THETA},
        {ClaimType::FIL, proto::CITEMTYPE_FIL},
        {ClaimType::TRX, proto::CITEMTYPE_TRX},
        {ClaimType::FTT, proto::CITEMTYPE_FTT},
        {ClaimType::ETC, proto::CITEMTYPE_ETC},
        {ClaimType::FTM, proto::CITEMTYPE_FTM},
        {ClaimType::DAI, proto::CITEMTYPE_DAI},
        {ClaimType::BTCB, proto::CITEMTYPE_BTCB},
        {ClaimType::EGLD, proto::CITEMTYPE_EGLD},
        {ClaimType::HBAR, proto::CITEMTYPE_HBAR},
        {ClaimType::XTZ, proto::CITEMTYPE_XTZ},
        {ClaimType::MANA, proto::CITEMTYPE_MANA},
        {ClaimType::Near, proto::CITEMTYPE_NEAR},
        {ClaimType::GRT, proto::CITEMTYPE_GRT},
        {ClaimType::CAKE, proto::CITEMTYPE_CAKE},
        {ClaimType::EOS, proto::CITEMTYPE_EOS},
        {ClaimType::FLOW, proto::CITEMTYPE_FLOW},
        {ClaimType::AAVE, proto::CITEMTYPE_AAVE},
        {ClaimType::KLAY, proto::CITEMTYPE_KLAY},
        {ClaimType::KSM, proto::CITEMTYPE_KSM},
        {ClaimType::XEC, proto::CITEMTYPE_XEC},
        {ClaimType::MIOTA, proto::CITEMTYPE_MIOTA},
        {ClaimType::HNT, proto::CITEMTYPE_HNT},
        {ClaimType::RUNE, proto::CITEMTYPE_RUNE},
        {ClaimType::BSV, proto::CITEMTYPE_BSV},
        {ClaimType::LEO, proto::CITEMTYPE_LEO},
        {ClaimType::NEO, proto::CITEMTYPE_NEO},
        {ClaimType::ONE, proto::CITEMTYPE_ONE},
        {ClaimType::QNT, proto::CITEMTYPE_QNT},
        {ClaimType::UST, proto::CITEMTYPE_UST},
        {ClaimType::MKR, proto::CITEMTYPE_MKR},
        {ClaimType::ENJ, proto::CITEMTYPE_ENJ},
        {ClaimType::CHZ, proto::CITEMTYPE_CHZ},
        {ClaimType::AR, proto::CITEMTYPE_AR},
        {ClaimType::STX, proto::CITEMTYPE_STX},
        {ClaimType::BTT, proto::CITEMTYPE_BTT},
        {ClaimType::HOT, proto::CITEMTYPE_HOT},
        {ClaimType::SAND, proto::CITEMTYPE_SAND},
        {ClaimType::OMG, proto::CITEMTYPE_OMG},
        {ClaimType::CELO, proto::CITEMTYPE_CELO},
        {ClaimType::ZEC, proto::CITEMTYPE_ZEC},
        {ClaimType::COMP, proto::CITEMTYPE_COMP},
        {ClaimType::TFUEL, proto::CITEMTYPE_TFUEL},
        {ClaimType::KDA, proto::CITEMTYPE_KDA},
        {ClaimType::LRC, proto::CITEMTYPE_LRC},
        {ClaimType::QTUM, proto::CITEMTYPE_QTUM},
        {ClaimType::CRV, proto::CITEMTYPE_CRV},
        {ClaimType::HT, proto::CITEMTYPE_HT},
        {ClaimType::NEXO, proto::CITEMTYPE_NEXO},
        {ClaimType::SUSHI, proto::CITEMTYPE_SUSHI},
        {ClaimType::KCS, proto::CITEMTYPE_KCS},
        {ClaimType::BAT, proto::CITEMTYPE_BAT},
        {ClaimType::OKB, proto::CITEMTYPE_OKB},
        {ClaimType::DCR, proto::CITEMTYPE_DCR},
        {ClaimType::ICX, proto::CITEMTYPE_ICX},
        {ClaimType::RVN, proto::CITEMTYPE_RVN},
        {ClaimType::SCRT, proto::CITEMTYPE_SCRT},
        {ClaimType::REV, proto::CITEMTYPE_REV},
        {ClaimType::AUDIO, proto::CITEMTYPE_AUDIO},
        {ClaimType::ZIL, proto::CITEMTYPE_ZIL},
        {ClaimType::TUSD, proto::CITEMTYPE_TUSD},
        {ClaimType::YFI, proto::CITEMTYPE_YFI},
        {ClaimType::MINA, proto::CITEMTYPE_MINA},
        {ClaimType::PERP, proto::CITEMTYPE_PERP},
        {ClaimType::XDC, proto::CITEMTYPE_XDC},
        {ClaimType::TEL, proto::CITEMTYPE_TEL},
        {ClaimType::SNX, proto::CITEMTYPE_SNX},
        {ClaimType::BTG, proto::CITEMTYPE_BTG},
        {ClaimType::AFN, proto::CITEMTYPE_AFN},
        {ClaimType::ALL, proto::CITEMTYPE_ALL},
        {ClaimType::AMD, proto::CITEMTYPE_AMD},
        {ClaimType::ANG, proto::CITEMTYPE_ANG},
        {ClaimType::AOA, proto::CITEMTYPE_AOA},
        {ClaimType::ARS, proto::CITEMTYPE_ARS},
        {ClaimType::AWG, proto::CITEMTYPE_AWG},
        {ClaimType::AZN, proto::CITEMTYPE_AZN},
        {ClaimType::BAM, proto::CITEMTYPE_BAM},
        {ClaimType::BBD, proto::CITEMTYPE_BBD},
        {ClaimType::BDT, proto::CITEMTYPE_BDT},
        {ClaimType::BGN, proto::CITEMTYPE_BGN},
        {ClaimType::BHD, proto::CITEMTYPE_BHD},
        {ClaimType::BIF, proto::CITEMTYPE_BIF},
        {ClaimType::BMD, proto::CITEMTYPE_BMD},
        {ClaimType::BND, proto::CITEMTYPE_BND},
        {ClaimType::BOB, proto::CITEMTYPE_BOB},
        {ClaimType::BRL, proto::CITEMTYPE_BRL},
        {ClaimType::BSD, proto::CITEMTYPE_BSD},
        {ClaimType::BTN, proto::CITEMTYPE_BTN},
        {ClaimType::BWP, proto::CITEMTYPE_BWP},
        {ClaimType::BYN, proto::CITEMTYPE_BYN},
        {ClaimType::BZD, proto::CITEMTYPE_BZD},
        {ClaimType::CDF, proto::CITEMTYPE_CDF},
        {ClaimType::CLP, proto::CITEMTYPE_CLP},
        {ClaimType::COP, proto::CITEMTYPE_COP},
        {ClaimType::CRC, proto::CITEMTYPE_CRC},
        {ClaimType::CUC, proto::CITEMTYPE_CUC},
        {ClaimType::CUP, proto::CITEMTYPE_CUP},
        {ClaimType::CVE, proto::CITEMTYPE_CVE},
        {ClaimType::CZK, proto::CITEMTYPE_CZK},
        {ClaimType::DJF, proto::CITEMTYPE_DJF},
        {ClaimType::DKK, proto::CITEMTYPE_DKK},
        {ClaimType::DOP, proto::CITEMTYPE_DOP},
        {ClaimType::DZD, proto::CITEMTYPE_DZD},
        {ClaimType::EGP, proto::CITEMTYPE_EGP},
        {ClaimType::ERN, proto::CITEMTYPE_ERN},
        {ClaimType::ETB, proto::CITEMTYPE_ETB},
        {ClaimType::FJD, proto::CITEMTYPE_FJD},
        {ClaimType::FKP, proto::CITEMTYPE_FKP},
        {ClaimType::GEL, proto::CITEMTYPE_GEL},
        {ClaimType::GGP, proto::CITEMTYPE_GGP},
        {ClaimType::GHS, proto::CITEMTYPE_GHS},
        {ClaimType::GIP, proto::CITEMTYPE_GIP},
        {ClaimType::GMD, proto::CITEMTYPE_GMD},
        {ClaimType::GNF, proto::CITEMTYPE_GNF},
        {ClaimType::GTQ, proto::CITEMTYPE_GTQ},
        {ClaimType::GYD, proto::CITEMTYPE_GYD},
        {ClaimType::HNL, proto::CITEMTYPE_HNL},
        {ClaimType::HRK, proto::CITEMTYPE_HRK},
        {ClaimType::HTG, proto::CITEMTYPE_HTG},
        {ClaimType::IDR, proto::CITEMTYPE_IDR},
        {ClaimType::ILS, proto::CITEMTYPE_ILS},
        {ClaimType::IMP, proto::CITEMTYPE_IMP},
        {ClaimType::IQD, proto::CITEMTYPE_IQD},
        {ClaimType::IRR, proto::CITEMTYPE_IRR},
        {ClaimType::ISK, proto::CITEMTYPE_ISK},
        {ClaimType::JEP, proto::CITEMTYPE_JEP},
        {ClaimType::JMD, proto::CITEMTYPE_JMD},
        {ClaimType::JOD, proto::CITEMTYPE_JOD},
        {ClaimType::KES, proto::CITEMTYPE_KES},
        {ClaimType::KGS, proto::CITEMTYPE_KGS},
        {ClaimType::KHR, proto::CITEMTYPE_KHR},
        {ClaimType::KMF, proto::CITEMTYPE_KMF},
        {ClaimType::KPW, proto::CITEMTYPE_KPW},
        {ClaimType::KRW, proto::CITEMTYPE_KRW},
        {ClaimType::KWD, proto::CITEMTYPE_KWD},
        {ClaimType::KYD, proto::CITEMTYPE_KYD},
        {ClaimType::KZT, proto::CITEMTYPE_KZT},
        {ClaimType::LAK, proto::CITEMTYPE_LAK},
        {ClaimType::LBP, proto::CITEMTYPE_LBP},
        {ClaimType::LKR, proto::CITEMTYPE_LKR},
        {ClaimType::LRD, proto::CITEMTYPE_LRD},
        {ClaimType::LSL, proto::CITEMTYPE_LSL},
        {ClaimType::LYD, proto::CITEMTYPE_LYD},
        {ClaimType::MAD, proto::CITEMTYPE_MAD},
        {ClaimType::MDL, proto::CITEMTYPE_MDL},
        {ClaimType::MGA, proto::CITEMTYPE_MGA},
        {ClaimType::MKD, proto::CITEMTYPE_MKD},
        {ClaimType::MMK, proto::CITEMTYPE_MMK},
        {ClaimType::MNT, proto::CITEMTYPE_MNT},
        {ClaimType::MOP, proto::CITEMTYPE_MOP},
        {ClaimType::MRU, proto::CITEMTYPE_MRU},
        {ClaimType::MUR, proto::CITEMTYPE_MUR},
        {ClaimType::MVR, proto::CITEMTYPE_MVR},
        {ClaimType::MWK, proto::CITEMTYPE_MWK},
        {ClaimType::MZN, proto::CITEMTYPE_MZN},
        {ClaimType::NAD, proto::CITEMTYPE_NAD},
        {ClaimType::NGN, proto::CITEMTYPE_NGN},
        {ClaimType::NIO, proto::CITEMTYPE_NIO},
        {ClaimType::NOK, proto::CITEMTYPE_NOK},
        {ClaimType::NPR, proto::CITEMTYPE_NPR},
        {ClaimType::OMR, proto::CITEMTYPE_OMR},
        {ClaimType::PAB, proto::CITEMTYPE_PAB},
        {ClaimType::PEN, proto::CITEMTYPE_PEN},
        {ClaimType::PGK, proto::CITEMTYPE_PGK},
        {ClaimType::PKR, proto::CITEMTYPE_PKR},
        {ClaimType::PLN, proto::CITEMTYPE_PLN},
        {ClaimType::PYG, proto::CITEMTYPE_PYG},
        {ClaimType::QAR, proto::CITEMTYPE_QAR},
        {ClaimType::RON, proto::CITEMTYPE_RON},
        {ClaimType::RSD, proto::CITEMTYPE_RSD},
        {ClaimType::RUB, proto::CITEMTYPE_RUB},
        {ClaimType::RWF, proto::CITEMTYPE_RWF},
        {ClaimType::SAR, proto::CITEMTYPE_SAR},
        {ClaimType::SBD, proto::CITEMTYPE_SBD},
        {ClaimType::SCR, proto::CITEMTYPE_SCR},
        {ClaimType::SDG, proto::CITEMTYPE_SDG},
        {ClaimType::SHP, proto::CITEMTYPE_SHP},
        {ClaimType::SLL, proto::CITEMTYPE_SLL},
        {ClaimType::SOS, proto::CITEMTYPE_SOS},
        {ClaimType::SPL, proto::CITEMTYPE_SPL},
        {ClaimType::SRD, proto::CITEMTYPE_SRD},
        {ClaimType::STN, proto::CITEMTYPE_STN},
        {ClaimType::SVC, proto::CITEMTYPE_SVC},
        {ClaimType::SYP, proto::CITEMTYPE_SYP},
        {ClaimType::SZL, proto::CITEMTYPE_SZL},
        {ClaimType::TJS, proto::CITEMTYPE_TJS},
        {ClaimType::TMT, proto::CITEMTYPE_TMT},
        {ClaimType::TND, proto::CITEMTYPE_TND},
        {ClaimType::TOP, proto::CITEMTYPE_TOP},
        {ClaimType::TRY, proto::CITEMTYPE_TRY},
        {ClaimType::TTD, proto::CITEMTYPE_TTD},
        {ClaimType::TVD, proto::CITEMTYPE_TVD},
        {ClaimType::TWD, proto::CITEMTYPE_TWD},
        {ClaimType::TZS, proto::CITEMTYPE_TZS},
        {ClaimType::UAH, proto::CITEMTYPE_UAH},
        {ClaimType::UGX, proto::CITEMTYPE_UGX},
        {ClaimType::UYU, proto::CITEMTYPE_UYU},
        {ClaimType::UZS, proto::CITEMTYPE_UZS},
        {ClaimType::VEF, proto::CITEMTYPE_VEF},
        {ClaimType::VND, proto::CITEMTYPE_VND},
        {ClaimType::VUV, proto::CITEMTYPE_VUV},
        {ClaimType::WST, proto::CITEMTYPE_WST},
        {ClaimType::XAF, proto::CITEMTYPE_XAF},
        {ClaimType::XCD, proto::CITEMTYPE_XCD},
        {ClaimType::XDR, proto::CITEMTYPE_XDR},
        {ClaimType::XOF, proto::CITEMTYPE_XOF},
        {ClaimType::XPF, proto::CITEMTYPE_XPF},
        {ClaimType::YER, proto::CITEMTYPE_YER},
        {ClaimType::ZMW, proto::CITEMTYPE_ZMW},
        {ClaimType::ZWD, proto::CITEMTYPE_ZWD},
    };

    return map;
}

auto sectiontype_map() noexcept -> const SectionTypeMap&
{
    static const auto map = SectionTypeMap{
        {SectionType::Error, proto::CONTACTSECTION_ERROR},
        {SectionType::Scope, proto::CONTACTSECTION_SCOPE},
        {SectionType::Identifier, proto::CONTACTSECTION_IDENTIFIER},
        {SectionType::Address, proto::CONTACTSECTION_ADDRESS},
        {SectionType::Communication, proto::CONTACTSECTION_COMMUNICATION},
        {SectionType::Profile, proto::CONTACTSECTION_PROFILE},
        {SectionType::Relationship, proto::CONTACTSECTION_RELATIONSHIP},
        {SectionType::Descriptor, proto::CONTACTSECTION_DESCRIPTOR},
        {SectionType::Event, proto::CONTACTSECTION_EVENT},
        {SectionType::Contract, proto::CONTACTSECTION_CONTRACT},
        {SectionType::Procedure, proto::CONTACTSECTION_PROCEDURE},
    };

    return map;
}

auto unittype_map() noexcept -> const UnitTypeMap&
{
    static const auto map = UnitTypeMap{
        {core::UnitType::Error, ClaimType::Error},
        {core::UnitType::BTC, ClaimType::BTC},
        {core::UnitType::ETH, ClaimType::ETH},
        {core::UnitType::XRP, ClaimType::XRP},
        {core::UnitType::LTC, ClaimType::LTC},
        {core::UnitType::DAO, ClaimType::DAO},
        {core::UnitType::XEM, ClaimType::XEM},
        {core::UnitType::DASH, ClaimType::DASH},
        {core::UnitType::MAID, ClaimType::MAID},
        {core::UnitType::LSK, ClaimType::LSK},
        {core::UnitType::DOGE, ClaimType::DOGE},
        {core::UnitType::DGD, ClaimType::DGD},
        {core::UnitType::XMR, ClaimType::XMR},
        {core::UnitType::WAVES, ClaimType::WAVES},
        {core::UnitType::NXT, ClaimType::NXT},
        {core::UnitType::SC, ClaimType::SC},
        {core::UnitType::STEEM, ClaimType::STEEM},
        {core::UnitType::AMP, ClaimType::AMP},
        {core::UnitType::XLM, ClaimType::XLM},
        {core::UnitType::FCT, ClaimType::FCT},
        {core::UnitType::BTS, ClaimType::BTS},
        {core::UnitType::USD, ClaimType::USD},
        {core::UnitType::EUR, ClaimType::EUR},
        {core::UnitType::GBP, ClaimType::GBP},
        {core::UnitType::INR, ClaimType::INR},
        {core::UnitType::AUD, ClaimType::AUD},
        {core::UnitType::CAD, ClaimType::CAD},
        {core::UnitType::SGD, ClaimType::SGD},
        {core::UnitType::CHF, ClaimType::CHF},
        {core::UnitType::MYR, ClaimType::MYR},
        {core::UnitType::JPY, ClaimType::JPY},
        {core::UnitType::CNY, ClaimType::CNY},
        {core::UnitType::NZD, ClaimType::NZD},
        {core::UnitType::THB, ClaimType::THB},
        {core::UnitType::HUF, ClaimType::HUF},
        {core::UnitType::AED, ClaimType::AED},
        {core::UnitType::HKD, ClaimType::HKD},
        {core::UnitType::MXN, ClaimType::MXN},
        {core::UnitType::ZAR, ClaimType::ZAR},
        {core::UnitType::PHP, ClaimType::PHP},
        {core::UnitType::SEK, ClaimType::SEK},
        {core::UnitType::TNBTC, ClaimType::TNBTC},
        {core::UnitType::TNXRP, ClaimType::TNXRP},
        {core::UnitType::TNLTX, ClaimType::TNLTX},
        {core::UnitType::TNXEM, ClaimType::TNXEM},
        {core::UnitType::TNDASH, ClaimType::TNDASH},
        {core::UnitType::TNMAID, ClaimType::TNMAID},
        {core::UnitType::TNLSK, ClaimType::TNLSK},
        {core::UnitType::TNDOGE, ClaimType::TNDOGE},
        {core::UnitType::TNXMR, ClaimType::TNXMR},
        {core::UnitType::TNWAVES, ClaimType::TNWAVES},
        {core::UnitType::TNNXT, ClaimType::TNNXT},
        {core::UnitType::TNSC, ClaimType::TNSC},
        {core::UnitType::TNSTEEM, ClaimType::TNSTEEM},
        {core::UnitType::BCH, ClaimType::BCH},
        {core::UnitType::TNBCH, ClaimType::TNBCH},
        {core::UnitType::PKT, ClaimType::PKT},
        {core::UnitType::TNPKT, ClaimType::TNPKT},
        {core::UnitType::Ethereum_Olympic, ClaimType::Ethereum_Olympic},
        {core::UnitType::Ethereum_Classic, ClaimType::Ethereum_Classic},
        {core::UnitType::Ethereum_Expanse, ClaimType::Ethereum_Expanse},
        {core::UnitType::Ethereum_Morden, ClaimType::Ethereum_Morden},
        {core::UnitType::Ethereum_Ropsten, ClaimType::Ethereum_Ropsten},
        {core::UnitType::Ethereum_Rinkeby, ClaimType::Ethereum_Rinkeby},
        {core::UnitType::Ethereum_Kovan, ClaimType::Ethereum_Kovan},
        {core::UnitType::Ethereum_Sokol, ClaimType::Ethereum_Sokol},
        {core::UnitType::Ethereum_POA, ClaimType::Ethereum_POA},
        {core::UnitType::Regtest, ClaimType::Regtest},
        {core::UnitType::Unknown, ClaimType::Unknown},
        {core::UnitType::BNB, ClaimType::BNB},
        {core::UnitType::SOL, ClaimType::SOL},
        {core::UnitType::USDT, ClaimType::USDT},
        {core::UnitType::ADA, ClaimType::ADA},
        {core::UnitType::DOT, ClaimType::DOT},
        {core::UnitType::USDC, ClaimType::USDC},
        {core::UnitType::SHIB, ClaimType::SHIB},
        {core::UnitType::LUNA, ClaimType::LUNA},
        {core::UnitType::AVAX, ClaimType::AVAX},
        {core::UnitType::UNI, ClaimType::UNI},
        {core::UnitType::LINK, ClaimType::LINK},
        {core::UnitType::WBTC, ClaimType::WBTC},
        {core::UnitType::BUSD, ClaimType::BUSD},
        {core::UnitType::MATIC, ClaimType::MATIC},
        {core::UnitType::ALGO, ClaimType::ALGO},
        {core::UnitType::VET, ClaimType::VET},
        {core::UnitType::AXS, ClaimType::AXS},
        {core::UnitType::ICP, ClaimType::ICP},
        {core::UnitType::CRO, ClaimType::CRO},
        {core::UnitType::ATOM, ClaimType::ATOM},
        {core::UnitType::THETA, ClaimType::THETA},
        {core::UnitType::FIL, ClaimType::FIL},
        {core::UnitType::TRX, ClaimType::TRX},
        {core::UnitType::FTT, ClaimType::FTT},
        {core::UnitType::ETC, ClaimType::ETC},
        {core::UnitType::FTM, ClaimType::FTM},
        {core::UnitType::DAI, ClaimType::DAI},
        {core::UnitType::BTCB, ClaimType::BTCB},
        {core::UnitType::EGLD, ClaimType::EGLD},
        {core::UnitType::HBAR, ClaimType::HBAR},
        {core::UnitType::XTZ, ClaimType::XTZ},
        {core::UnitType::MANA, ClaimType::MANA},
        {core::UnitType::Near, ClaimType::Near},
        {core::UnitType::GRT, ClaimType::GRT},
        {core::UnitType::CAKE, ClaimType::CAKE},
        {core::UnitType::EOS, ClaimType::EOS},
        {core::UnitType::FLOW, ClaimType::FLOW},
        {core::UnitType::AAVE, ClaimType::AAVE},
        {core::UnitType::KLAY, ClaimType::KLAY},
        {core::UnitType::KSM, ClaimType::KSM},
        {core::UnitType::XEC, ClaimType::XEC},
        {core::UnitType::MIOTA, ClaimType::MIOTA},
        {core::UnitType::HNT, ClaimType::HNT},
        {core::UnitType::RUNE, ClaimType::RUNE},
        {core::UnitType::BSV, ClaimType::BSV},
        {core::UnitType::LEO, ClaimType::LEO},
        {core::UnitType::NEO, ClaimType::NEO},
        {core::UnitType::ONE, ClaimType::ONE},
        {core::UnitType::QNT, ClaimType::QNT},
        {core::UnitType::UST, ClaimType::UST},
        {core::UnitType::MKR, ClaimType::MKR},
        {core::UnitType::ENJ, ClaimType::ENJ},
        {core::UnitType::CHZ, ClaimType::CHZ},
        {core::UnitType::AR, ClaimType::AR},
        {core::UnitType::STX, ClaimType::STX},
        {core::UnitType::BTT, ClaimType::BTT},
        {core::UnitType::HOT, ClaimType::HOT},
        {core::UnitType::SAND, ClaimType::SAND},
        {core::UnitType::OMG, ClaimType::OMG},
        {core::UnitType::CELO, ClaimType::CELO},
        {core::UnitType::ZEC, ClaimType::ZEC},
        {core::UnitType::COMP, ClaimType::COMP},
        {core::UnitType::TFUEL, ClaimType::TFUEL},
        {core::UnitType::KDA, ClaimType::KDA},
        {core::UnitType::LRC, ClaimType::LRC},
        {core::UnitType::QTUM, ClaimType::QTUM},
        {core::UnitType::CRV, ClaimType::CRV},
        {core::UnitType::HT, ClaimType::HT},
        {core::UnitType::NEXO, ClaimType::NEXO},
        {core::UnitType::SUSHI, ClaimType::SUSHI},
        {core::UnitType::KCS, ClaimType::KCS},
        {core::UnitType::BAT, ClaimType::BAT},
        {core::UnitType::OKB, ClaimType::OKB},
        {core::UnitType::DCR, ClaimType::DCR},
        {core::UnitType::ICX, ClaimType::ICX},
        {core::UnitType::RVN, ClaimType::RVN},
        {core::UnitType::SCRT, ClaimType::SCRT},
        {core::UnitType::REV, ClaimType::REV},
        {core::UnitType::AUDIO, ClaimType::AUDIO},
        {core::UnitType::ZIL, ClaimType::ZIL},
        {core::UnitType::TUSD, ClaimType::TUSD},
        {core::UnitType::YFI, ClaimType::YFI},
        {core::UnitType::MINA, ClaimType::MINA},
        {core::UnitType::PERP, ClaimType::PERP},
        {core::UnitType::XDC, ClaimType::XDC},
        {core::UnitType::TEL, ClaimType::TEL},
        {core::UnitType::SNX, ClaimType::SNX},
        {core::UnitType::BTG, ClaimType::BTG},
        {core::UnitType::AFN, ClaimType::AFN},
        {core::UnitType::ALL, ClaimType::ALL},
        {core::UnitType::AMD, ClaimType::AMD},
        {core::UnitType::ANG, ClaimType::ANG},
        {core::UnitType::AOA, ClaimType::AOA},
        {core::UnitType::ARS, ClaimType::ARS},
        {core::UnitType::AWG, ClaimType::AWG},
        {core::UnitType::AZN, ClaimType::AZN},
        {core::UnitType::BAM, ClaimType::BAM},
        {core::UnitType::BBD, ClaimType::BBD},
        {core::UnitType::BDT, ClaimType::BDT},
        {core::UnitType::BGN, ClaimType::BGN},
        {core::UnitType::BHD, ClaimType::BHD},
        {core::UnitType::BIF, ClaimType::BIF},
        {core::UnitType::BMD, ClaimType::BMD},
        {core::UnitType::BND, ClaimType::BND},
        {core::UnitType::BOB, ClaimType::BOB},
        {core::UnitType::BRL, ClaimType::BRL},
        {core::UnitType::BsD, ClaimType::BSD},
        {core::UnitType::BTN, ClaimType::BTN},
        {core::UnitType::BWP, ClaimType::BWP},
        {core::UnitType::BYN, ClaimType::BYN},
        {core::UnitType::BZD, ClaimType::BZD},
        {core::UnitType::CDF, ClaimType::CDF},
        {core::UnitType::CLP, ClaimType::CLP},
        {core::UnitType::COP, ClaimType::COP},
        {core::UnitType::CRC, ClaimType::CRC},
        {core::UnitType::CUC, ClaimType::CUC},
        {core::UnitType::CUP, ClaimType::CUP},
        {core::UnitType::CVE, ClaimType::CVE},
        {core::UnitType::CZK, ClaimType::CZK},
        {core::UnitType::DJF, ClaimType::DJF},
        {core::UnitType::DKK, ClaimType::DKK},
        {core::UnitType::DOP, ClaimType::DOP},
        {core::UnitType::DZD, ClaimType::DZD},
        {core::UnitType::EGP, ClaimType::EGP},
        {core::UnitType::ERN, ClaimType::ERN},
        {core::UnitType::ETB, ClaimType::ETB},
        {core::UnitType::FJD, ClaimType::FJD},
        {core::UnitType::FKP, ClaimType::FKP},
        {core::UnitType::GEL, ClaimType::GEL},
        {core::UnitType::GGP, ClaimType::GGP},
        {core::UnitType::GHS, ClaimType::GHS},
        {core::UnitType::GIP, ClaimType::GIP},
        {core::UnitType::GMD, ClaimType::GMD},
        {core::UnitType::GNF, ClaimType::GNF},
        {core::UnitType::GTQ, ClaimType::GTQ},
        {core::UnitType::GYD, ClaimType::GYD},
        {core::UnitType::HNL, ClaimType::HNL},
        {core::UnitType::HRK, ClaimType::HRK},
        {core::UnitType::HTG, ClaimType::HTG},
        {core::UnitType::IDR, ClaimType::IDR},
        {core::UnitType::ILS, ClaimType::ILS},
        {core::UnitType::IMP, ClaimType::IMP},
        {core::UnitType::IQD, ClaimType::IQD},
        {core::UnitType::IRR, ClaimType::IRR},
        {core::UnitType::ISK, ClaimType::ISK},
        {core::UnitType::JEP, ClaimType::JEP},
        {core::UnitType::JMD, ClaimType::JMD},
        {core::UnitType::JOD, ClaimType::JOD},
        {core::UnitType::KES, ClaimType::KES},
        {core::UnitType::KGS, ClaimType::KGS},
        {core::UnitType::KHR, ClaimType::KHR},
        {core::UnitType::KMF, ClaimType::KMF},
        {core::UnitType::KPW, ClaimType::KPW},
        {core::UnitType::KRW, ClaimType::KRW},
        {core::UnitType::KWD, ClaimType::KWD},
        {core::UnitType::KYD, ClaimType::KYD},
        {core::UnitType::KZT, ClaimType::KZT},
        {core::UnitType::LAK, ClaimType::LAK},
        {core::UnitType::LBP, ClaimType::LBP},
        {core::UnitType::LKR, ClaimType::LKR},
        {core::UnitType::LRD, ClaimType::LRD},
        {core::UnitType::LSL, ClaimType::LSL},
        {core::UnitType::LYD, ClaimType::LYD},
        {core::UnitType::MAD, ClaimType::MAD},
        {core::UnitType::MDL, ClaimType::MDL},
        {core::UnitType::MGA, ClaimType::MGA},
        {core::UnitType::MKD, ClaimType::MKD},
        {core::UnitType::MMK, ClaimType::MMK},
        {core::UnitType::MNT, ClaimType::MNT},
        {core::UnitType::MOP, ClaimType::MOP},
        {core::UnitType::MRU, ClaimType::MRU},
        {core::UnitType::MUR, ClaimType::MUR},
        {core::UnitType::MVR, ClaimType::MVR},
        {core::UnitType::MWK, ClaimType::MWK},
        {core::UnitType::MZN, ClaimType::MZN},
        {core::UnitType::NAD, ClaimType::NAD},
        {core::UnitType::NGN, ClaimType::NGN},
        {core::UnitType::NIO, ClaimType::NIO},
        {core::UnitType::NOK, ClaimType::NOK},
        {core::UnitType::NPR, ClaimType::NPR},
        {core::UnitType::OMR, ClaimType::OMR},
        {core::UnitType::PAB, ClaimType::PAB},
        {core::UnitType::PEN, ClaimType::PEN},
        {core::UnitType::PGK, ClaimType::PGK},
        {core::UnitType::PKR, ClaimType::PKR},
        {core::UnitType::PLN, ClaimType::PLN},
        {core::UnitType::PYG, ClaimType::PYG},
        {core::UnitType::QAR, ClaimType::QAR},
        {core::UnitType::RON, ClaimType::RON},
        {core::UnitType::RSD, ClaimType::RSD},
        {core::UnitType::RUB, ClaimType::RUB},
        {core::UnitType::RWF, ClaimType::RWF},
        {core::UnitType::SAR, ClaimType::SAR},
        {core::UnitType::SBD, ClaimType::SBD},
        {core::UnitType::SCR, ClaimType::SCR},
        {core::UnitType::SDG, ClaimType::SDG},
        {core::UnitType::SHP, ClaimType::SHP},
        {core::UnitType::SLL, ClaimType::SLL},
        {core::UnitType::SOS, ClaimType::SOS},
        {core::UnitType::SPL, ClaimType::SPL},
        {core::UnitType::SRD, ClaimType::SRD},
        {core::UnitType::STN, ClaimType::STN},
        {core::UnitType::SVC, ClaimType::SVC},
        {core::UnitType::SYP, ClaimType::SYP},
        {core::UnitType::SZL, ClaimType::SZL},
        {core::UnitType::TJS, ClaimType::TJS},
        {core::UnitType::TMT, ClaimType::TMT},
        {core::UnitType::TND, ClaimType::TND},
        {core::UnitType::TOP, ClaimType::TOP},
        {core::UnitType::TRY, ClaimType::TRY},
        {core::UnitType::TTD, ClaimType::TTD},
        {core::UnitType::TVD, ClaimType::TVD},
        {core::UnitType::TWD, ClaimType::TWD},
        {core::UnitType::TZS, ClaimType::TZS},
        {core::UnitType::UAH, ClaimType::UAH},
        {core::UnitType::UGX, ClaimType::UGX},
        {core::UnitType::UYU, ClaimType::UYU},
        {core::UnitType::UZS, ClaimType::UZS},
        {core::UnitType::VEF, ClaimType::VEF},
        {core::UnitType::VND, ClaimType::VND},
        {core::UnitType::VUV, ClaimType::VUV},
        {core::UnitType::WST, ClaimType::WST},
        {core::UnitType::XAF, ClaimType::XAF},
        {core::UnitType::XCD, ClaimType::XCD},
        {core::UnitType::XDR, ClaimType::XDR},
        {core::UnitType::XOF, ClaimType::XOF},
        {core::UnitType::XPF, ClaimType::XPF},
        {core::UnitType::YER, ClaimType::YER},
        {core::UnitType::ZMW, ClaimType::ZMW},
        {core::UnitType::ZWD, ClaimType::ZWD},
    };

    return map;
}
}  // namespace opentxs::contact

namespace opentxs
{
auto ClaimToUnit(const contact::ClaimType in) noexcept -> core::UnitType
{
    static const auto map = reverse_arbitrary_map<
        core::UnitType,
        contact::ClaimType,
        contact::UnitTypeReverseMap>(contact::unittype_map());

    try {
        return map.at(in);
    } catch (...) {
        return core::UnitType::Error;
    }
}

auto translate(const contact::Attribute in) noexcept
    -> proto::ContactItemAttribute
{
    try {
        return contact::attribute_map().at(in);
    } catch (...) {
        return proto::CITEMATTR_ERROR;
    }
}

auto translate(const contact::ClaimType in) noexcept -> proto::ContactItemType
{
    try {
        return contact::claimtype_map().at(in);
    } catch (...) {
        return proto::CITEMTYPE_ERROR;
    }
}

auto translate(const contact::SectionType in) noexcept
    -> proto::ContactSectionName
{
    try {
        return contact::sectiontype_map().at(in);
    } catch (...) {
        return proto::CONTACTSECTION_ERROR;
    }
}

auto translate(const proto::ContactItemAttribute in) noexcept
    -> contact::Attribute
{
    static const auto map = reverse_arbitrary_map<
        contact::Attribute,
        proto::ContactItemAttribute,
        contact::AttributeReverseMap>(contact::attribute_map());

    try {
        return map.at(in);
    } catch (...) {
        return contact::Attribute::Error;
    }
}

auto translate(const proto::ContactItemType in) noexcept -> contact::ClaimType
{
    static const auto map = reverse_arbitrary_map<
        contact::ClaimType,
        proto::ContactItemType,
        contact::ClaimTypeReverseMap>(contact::claimtype_map());

    try {
        return map.at(in);
    } catch (...) {
        return contact::ClaimType::Error;
    }
}

auto translate(const proto::ContactSectionName in) noexcept
    -> contact::SectionType
{
    static const auto map = reverse_arbitrary_map<
        contact::SectionType,
        proto::ContactSectionName,
        contact::SectionTypeReverseMap>(contact::sectiontype_map());

    try {
        return map.at(in);
    } catch (...) {
        return contact::SectionType::Error;
    }
}

auto UnitToClaim(const core::UnitType in) noexcept -> contact::ClaimType
{
    try {
        return contact::unittype_map().at(in);
    } catch (...) {
        return contact::ClaimType::Error;
    }
}
}  // namespace opentxs
