// Copyright (c) 2010-2021 The Open-Transactions developers
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

#pragma once

#include "opentxs/core/Types.hpp"  // IWYU pragma: associated

#include <cstdint>
#include <limits>

#include "opentxs/contact/Types.hpp"

namespace opentxs
{
namespace core
{
enum class UnitType : std::uint32_t {
    Error = 0,
    BTC = 1,
    BCH = 2,
    ETH = 3,
    XRP = 4,
    LTC = 5,
    DAO = 6,
    XEM = 7,
    DASH = 8,
    MAID = 9,
    LSK = 10,
    DOGE = 11,
    DGD = 12,
    XMR = 13,
    WAVES = 14,
    NXT = 15,
    SC = 16,
    STEEM = 17,
    AMP = 18,
    XLM = 19,
    FCT = 20,
    BTS = 21,
    USD = 22,
    EUR = 23,
    GBP = 24,
    INR = 25,
    AUD = 26,
    CAD = 27,
    SGD = 28,
    CHF = 29,
    MYR = 30,
    JPY = 31,
    CNY = 32,
    NZD = 33,
    THB = 34,
    HUF = 35,
    AED = 36,
    HKD = 37,
    MXN = 38,
    ZAR = 39,
    PHP = 40,
    SEK = 41,
    PKT = 42,
    TNBTC = 43,
    TNBCH = 44,
    TNXRP = 45,
    TNLTX = 46,
    TNXEM = 47,
    TNDASH = 48,
    TNMAID = 49,
    TNLSK = 50,
    TNDOGE = 51,
    TNXMR = 52,
    TNWAVES = 53,
    TNNXT = 54,
    TNSC = 55,
    TNSTEEM = 56,
    TNPKT = 57,
    Ethereum_Olympic = 58,
    Ethereum_Classic = 59,
    Ethereum_Expanse = 60,
    Ethereum_Morden = 61,
    Ethereum_Ropsten = 62,
    Ethereum_Rinkeby = 63,
    Ethereum_Kovan = 64,
    Ethereum_Sokol = 65,
    Ethereum_POA = 66,
    Regtest = 67,
    BNB = 68,     // Binance Coin
    SOL = 69,     // Solana
    USDT = 70,    // Tether
    ADA = 71,     // Cardano
    DOT = 72,     // Polkadot
    USDC = 73,    // USD Coin
    SHIB = 74,    // SHIBA INU
    LUNA = 75,    // Terra
    AVAX = 76,    // Avalanche
    UNI = 77,     // Uniswap
    LINK = 78,    // Chainlink
    WBTC = 79,    // Wrapped Bitcoin
    BUSD = 80,    // Binance USD
    MATIC = 81,   // Polygon
    ALGO = 82,    // Algorand
    VET = 83,     // VeChain
    AXS = 84,     // Axie Infinity
    ICP = 85,     // Internet Computer
    CRO = 86,     // Crypto.com Coin
    ATOM = 87,    // Cosmos
    THETA = 88,   // THETA
    FIL = 89,     // Filecoin
    TRX = 90,     // TRON
    FTT = 91,     // FTX Token
    ETC = 92,     // Ethereum Classic
    FTM = 93,     // Fantom
    DAI = 94,     // Dai
    BTCB = 95,    // Bitcoin BEP2
    EGLD = 96,    // Elrond
    HBAR = 97,    // Hedera
    XTZ = 98,     // Tezos
    MANA = 99,    // Decentraland
    Near = 100,   // NEAR Protocol
    GRT = 101,    // The Graph
    CAKE = 102,   // PancakeSwap
    EOS = 103,    // EOS
    FLOW = 104,   // Flow
    AAVE = 105,   // Aave
    KLAY = 106,   // Klaytn
    KSM = 107,    // Kusama
    XEC = 108,    // eCash
    MIOTA = 109,  // IOTA
    HNT = 110,    // Helium
    RUNE = 111,   // THORChain
    BSV = 112,    // Bitcoin SV
    LEO = 113,    // UNUS SED LEO
    NEO = 114,    // Neo
    ONE = 115,    // Harmony
    QNT = 116,    // Quant
    UST = 117,    // TerraUSD
    MKR = 118,    // Maker
    ENJ = 119,    // Enjin Coin
    CHZ = 120,    // Chiliz
    AR = 121,     // Arweave
    STX = 122,    // Stacks
    BTT = 123,    // BitTorrent
    HOT = 124,    // Holo
    SAND = 125,   // The Sandbox
    OMG = 126,    // OMG Network
    CELO = 127,   // Celo
    ZEC = 128,    // Zcash
    COMP = 129,   // Compound
    TFUEL = 130,  // Theta Fuel
    KDA = 131,    // Kadena
    LRC = 132,    // Loopring
    QTUM = 133,   // Qtum
    CRV = 134,    // Curve DAO Token
    HT = 135,     // Huobi Token
    NEXO = 136,   // Nexo
    SUSHI = 137,  // SushiSwap
    KCS = 138,    // KuCoin Token
    BAT = 139,    // Basic Attention Token
    OKB = 140,    // OKB
    DCR = 141,    // Decred
    ICX = 142,    // ICON
    RVN = 143,    // Ravencoin
    SCRT = 144,   // Secret
    REV = 145,    // Revain
    AUDIO = 146,  // Audius
    ZIL = 147,    // Zilliqa
    TUSD = 148,   // TrueUSD
    YFI = 149,    // yearn.finance
    MINA = 150,   // Mina
    PERP = 151,   // Perpetual Protocol
    XDC = 152,    // XDC Network
    TEL = 153,    // Telcoin
    SNX = 154,    // Synthetix
    BTG = 155,    // Bitcoin Gold
    AFN = 156,    // Afghanistan Afghani
    ALL = 157,    // Albania Lek
    AMD = 158,    // Armenia Dram
    ANG = 159,    // Netherlands Antilles Guilder
    AOA = 160,    // Angola Kwanza
    ARS = 161,    // Argentina Peso
    AWG = 162,    // Aruba Guilder
    AZN = 163,    // Azerbaijan Manat
    BAM = 164,    // Bosnia and Herzegovina Convertible Mark
    BBD = 165,    // Barbados Dollar
    BDT = 166,    // Bangladesh Taka
    BGN = 167,    // Bulgaria Lev
    BHD = 168,    // Bahrain Dinar
    BIF = 169,    // Burundi Franc
    BMD = 170,    // Bermuda Dollar
    BND = 171,    // Brunei Darussalam Dollar
    BOB = 172,    // Bolivia Bolíviano
    BRL = 173,    // Brazil Real
    BsD = 174,    // Bahamas Dollar
    BTN = 175,    // Bhutan Ngultrum
    BWP = 176,    // Botswana Pula
    BYN = 177,    // Belarus Ruble
    BZD = 178,    // Belize Dollar
    CDF = 179,    // Congo/Kinshasa Franc
    CLP = 180,    // Chile Peso
    COP = 181,    // Colombia Peso
    CRC = 182,    // Costa Rica Colon
    CUC = 183,    // Cuba Convertible Peso
    CUP = 184,    // Cuba Peso
    CVE = 185,    // Cape Verde Escudo
    CZK = 186,    // Czech Republic Koruna
    DJF = 187,    // Djibouti Franc
    DKK = 188,    // Denmark Krone
    DOP = 189,    // Dominican Republic Peso
    DZD = 190,    // Algeria Dinar
    EGP = 191,    // Egypt Pound
    ERN = 192,    // Eritrea Nakfa
    ETB = 193,    // Ethiopia Birr
    FJD = 194,    // Fiji Dollar
    FKP = 195,    // Falkland Islands (Malvinas) Pound
    GEL = 196,    // Georgia Lari
    GGP = 197,    // Guernsey Pound
    GHS = 198,    // Ghana Cedi
    GIP = 199,    // Gibraltar Pound
    GMD = 200,    // Gambia Dalasi
    GNF = 201,    // Guinea Franc
    GTQ = 202,    // Guatemala Quetzal
    GYD = 203,    // Guyana Dollar
    HNL = 204,    // Honduras Lempira
    HRK = 205,    // Croatia Kuna
    HTG = 206,    // Haiti Gourde
    IDR = 207,    // Indonesia Rupiah
    ILS = 208,    // Israel Shekel
    IMP = 209,    // Isle of Man Pound
    IQD = 210,    // Iraq Dinar
    IRR = 211,    // Iran Rial
    ISK = 212,    // Iceland Krona
    JEP = 213,    // Jersey Pound
    JMD = 214,    // Jamaica Dollar
    JOD = 215,    // Jordan Dinar
    KES = 216,    // Kenya Shilling
    KGS = 217,    // Kyrgyzstan Som
    KHR = 218,    // Cambodia Riel
    KMF = 219,    // Comorian Franc
    KPW = 220,    // Korea (North) Won
    KRW = 221,    // Korea (South) Won
    KWD = 222,    // Kuwait Dinar
    KYD = 223,    // Cayman Islands Dollar
    KZT = 224,    // Kazakhstan Tenge
    LAK = 225,    // Laos Kip
    LBP = 226,    // Lebanon Pound
    LKR = 227,    // Sri Lanka Rupee
    LRD = 228,    // Liberia Dollar
    LSL = 229,    // Lesotho Loti
    LYD = 230,    // Libya Dinar
    MAD = 231,    // Morocco Dirham
    MDL = 232,    // Moldova Leu
    MGA = 233,    // Madagascar Ariary
    MKD = 234,    // Macedonia Denar
    MMK = 235,    // Myanmar (Burma) Kyat
    MNT = 236,    // Mongolia Tughrik
    MOP = 237,    // Macau Pataca
    MRU = 238,    // Mauritania Ouguiya
    MUR = 239,    // Mauritius Rupee
    MVR = 240,    // Maldives (Maldive Islands) Rufiyaa
    MWK = 241,    // Malawi Kwacha
    MZN = 242,    // Mozambique Metical
    NAD = 243,    // Namibia Dollar
    NGN = 244,    // Nigeria Naira
    NIO = 245,    // Nicaragua Cordoba
    NOK = 246,    // Norway Krone
    NPR = 247,    // Nepal Rupee
    OMR = 248,    // Oman Rial
    PAB = 249,    // Panama Balboa
    PEN = 250,    // Peru Sol
    PGK = 251,    // Papua New Guinea Kina
    PKR = 252,    // Pakistan Rupee
    PLN = 253,    // Poland Zloty
    PYG = 254,    // Paraguay Guarani
    QAR = 255,    // Qatar Riyal
    RON = 256,    // Romania Leu
    RSD = 257,    // Serbia Dinar
    RUB = 258,    // Russia Ruble
    RWF = 259,    // Rwanda Franc
    SAR = 260,    // Saudi Arabia Riyal
    SBD = 261,    // Solomon Islands Dollar
    SCR = 262,    // Seychelles Rupee
    SDG = 263,    // Sudan Pound
    SHP = 264,    // Saint Helena Pound
    SLL = 265,    // Sierra Leone Leone
    SOS = 266,    // Somalia Shilling
    SPL = 267,    // Seborga Luigino
    SRD = 268,    // Suriname Dollar
    STN = 269,    // São Tomé and Príncipe Dobra
    SVC = 270,    // El Salvador Colon
    SYP = 271,    // Syria Pound
    SZL = 272,    // eSwatini Lilangeni
    TJS = 273,    // Tajikistan Somoni
    TMT = 274,    // Turkmenistan Manat
    TND = 275,    // Tunisia Dinar
    TOP = 276,    // Tonga Pa'anga
    TRY = 277,    // Turkey Lira
    TTD = 278,    // Trinidad and Tobago Dollar
    TVD = 279,    // Tuvalu Dollar
    TWD = 280,    // Taiwan New Dollar
    TZS = 281,    // Tanzania Shilling
    UAH = 282,    // Ukraine Hryvnia
    UGX = 283,    // Uganda Shilling
    UYU = 284,    // Uruguay Peso
    UZS = 285,    // Uzbekistan Som
    VEF = 286,    // Venezuela Bolívar
    VND = 287,    // Viet Nam Dong
    VUV = 288,    // Vanuatu Vatu
    WST = 289,    // Samoa Tala
    XAF = 290,    // Communauté Financière Africaine (BEAC) CFA Franc BEAC
    XCD = 291,    // East Caribbean Dollar
    XDR = 292,    // International Monetary Fund (IMF) Special Drawing Rights
    XOF = 293,    // Communauté Financière Africaine (BCEAO) Franc
    XPF = 294,    // Comptoirs Français du Pacifique (CFP) Franc
    YER = 295,    // Yemen Rial
    ZMW = 296,    // Zambia Kwacha
    ZWD = 297,    // Zimbabwe Dollar
    Custom = 298,

    Unknown = std::numeric_limits<std::uint32_t>::max(),
};

}  // namespace core
}  // namespace opentxs
