// Copyright (c) 2010-2021 The Open-Transactions developers
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

#pragma once

#include "opentxs/Version.hpp"                   // IWYU pragma: associated
#include "opentxs/identity/wot/claim/Types.hpp"  // IWYU pragma: associated

#include <cstdint>

namespace opentxs::identity::wot::claim
{
enum class ClaimType : std::uint32_t {
    Error = 0,
    Individual = 1,
    Organization = 2,
    Business = 3,
    Government = 4,
    Server = 5,
    Prefix = 6,
    Forename = 7,
    Middlename = 8,
    Surname = 9,
    Pedigree = 10,
    Suffix = 11,
    Nickname = 12,
    Commonname = 13,
    Passport = 14,
    National = 15,
    Provincial = 16,
    Military = 17,
    PGP = 18,
    OTR = 19,
    SSL = 20,
    Physical = 21,
    Official = 22,
    Birthplace = 23,
    Home = 24,
    Website = 25,
    Opentxs = 26,
    Phone = 27,
    Email = 28,
    Skype = 29,
    Wire = 30,
    QQ = 31,
    Bitmessage = 32,
    Whatsapp = 33,
    Telegram = 34,
    KIK = 35,
    BBM = 36,
    Wechat = 37,
    Kakaotalk = 38,
    Facebook = 39,
    Google = 40,
    Linkedin = 41,
    VK = 42,
    Aboutme = 43,
    Onename = 44,
    Twitter = 45,
    Medium = 46,
    Tumblr = 47,
    Yahoo = 48,
    Myspace = 49,
    Meetup = 50,
    Reddit = 51,
    Hackernews = 52,
    Wikipedia = 53,
    Angellist = 54,
    Github = 55,
    Bitbucket = 56,
    Youtube = 57,
    Vimeo = 58,
    Twitch = 59,
    Snapchat = 60,
    Vine = 61,
    Instagram = 62,
    Pinterest = 63,
    Imgur = 64,
    Flickr = 65,
    Dribble = 66,
    Behance = 67,
    Deviantart = 68,
    Spotify = 69,
    Itunes = 70,
    Soundcloud = 71,
    Askfm = 72,
    Ebay = 73,
    Etsy = 74,
    Openbazaar = 75,
    Xboxlive = 76,
    Playstation = 77,
    Secondlife = 78,
    Warcraft = 79,
    Alias = 80,
    Acquaintance = 81,
    Friend = 82,
    Spouse = 83,
    Sibling = 84,
    Member = 85,
    Colleague = 86,
    Parent = 87,
    Child = 88,
    Employer = 89,
    Employee = 90,
    Citizen = 91,
    Photo = 92,
    Gender = 93,
    Height = 94,
    Weight = 95,
    Hair = 96,
    Eye = 97,
    Skin = 98,
    Ethnicity = 99,
    Language = 100,
    Degree = 101,
    Certification = 102,
    Title = 103,
    Skill = 104,
    Award = 105,
    Likes = 106,
    Sexual = 107,
    Political = 108,
    Religious = 109,
    Birth = 110,
    Secondarygraduation = 111,
    Universitygraduation = 112,
    Wedding = 113,
    Accomplishment = 114,
    BTC = 115,
    ETH = 116,
    XRP = 117,
    LTC = 118,
    DAO = 119,
    XEM = 120,
    DASH = 121,
    MAID = 122,
    LSK = 123,
    DOGE = 124,
    DGD = 125,
    XMR = 126,
    WAVES = 127,
    NXT = 128,
    SC = 129,
    STEEM = 130,
    AMP = 131,
    XLM = 132,
    FCT = 133,
    BTS = 134,
    USD = 135,
    EUR = 136,
    GBP = 137,
    INR = 138,
    AUD = 139,
    CAD = 140,
    SGD = 141,
    CHF = 142,
    MYR = 143,
    JPY = 144,
    CNY = 145,
    NZD = 146,
    THB = 147,
    HUF = 148,
    AED = 149,
    HKD = 150,
    MXN = 151,
    ZAR = 152,
    PHP = 153,
    SEK = 154,
    TNBTC = 155,
    TNXRP = 156,
    TNLTX = 157,
    TNXEM = 158,
    TNDASH = 159,
    TNMAID = 160,
    TNLSK = 161,
    TNDOGE = 162,
    TNXMR = 163,
    TNWAVES = 164,
    TNNXT = 165,
    TNSC = 166,
    TNSTEEM = 167,
    Philosophy = 168,
    Met = 169,
    Fan = 170,
    Supervisor = 171,
    Subordinate = 172,
    Contact = 173,
    Refreshed = 174,
    BOT = 175,
    BCH = 176,
    TNBCH = 177,
    Owner = 178,
    Property = 179,
    Unknown = 180,
    Ethereum_Olympic = 181,
    Ethereum_Classic = 182,
    Ethereum_Expanse = 183,
    Ethereum_Morden = 184,
    Ethereum_Ropsten = 185,
    Ethereum_Rinkeby = 186,
    Ethereum_Kovan = 187,
    Ethereum_Sokol = 188,
    Ethereum_POA = 189,
    PKT = 190,
    TNPKT = 191,
    Regtest = 192,
    BNB = 193,    // Binance Coin
    SOL = 194,    // Solana
    USDT = 195,   // Tether
    ADA = 196,    // Cardano
    DOT = 197,    // Polkadot
    USDC = 198,   // USD Coin
    SHIB = 199,   // SHIBA INU
    LUNA = 200,   // Terra
    AVAX = 201,   // Avalanche
    UNI = 202,    // Uniswap
    LINK = 203,   // Chainlink
    WBTC = 204,   // Wrapped Bitcoin
    BUSD = 205,   // Binance USD
    MATIC = 206,  // Polygon
    ALGO = 207,   // Algorand
    VET = 208,    // VeChain
    AXS = 209,    // Axie Infinity
    ICP = 210,    // Internet Computer
    CRO = 211,    // Crypto.com Coin
    ATOM = 212,   // Cosmos
    THETA = 213,  // THETA
    FIL = 214,    // Filecoin
    TRX = 215,    // TRON
    FTT = 216,    // FTX Token
    ETC = 217,    // Ethereum Classic
    FTM = 218,    // Fantom
    DAI = 219,    // Dai
    BTCB = 220,   // Bitcoin BEP2
    EGLD = 221,   // Elrond
    HBAR = 222,   // Hedera
    XTZ = 223,    // Tezos
    MANA = 224,   // Decentraland
    Near = 225,   // NEAR Protocol
    GRT = 226,    // The Graph
    CAKE = 227,   // PancakeSwap
    EOS = 228,    // EOS
    FLOW = 229,   // Flow
    AAVE = 230,   // Aave
    KLAY = 231,   // Klaytn
    KSM = 232,    // Kusama
    XEC = 233,    // eCash
    MIOTA = 234,  // IOTA
    HNT = 235,    // Helium
    RUNE = 236,   // THORChain
    BSV = 237,    // Bitcoin SV
    LEO = 238,    // UNUS SED LEO
    NEO = 239,    // Neo
    ONE = 240,    // Harmony
    QNT = 241,    // Quant
    UST = 242,    // TerraUSD
    MKR = 243,    // Maker
    ENJ = 244,    // Enjin Coin
    CHZ = 245,    // Chiliz
    AR = 246,     // Arweave
    STX = 247,    // Stacks
    BTT = 248,    // BitTorrent
    HOT = 249,    // Holo
    SAND = 250,   // The Sandbox
    OMG = 251,    // OMG Network
    CELO = 252,   // Celo
    ZEC = 253,    // Zcash
    COMP = 254,   // Compound
    TFUEL = 255,  // Theta Fuel
    KDA = 256,    // Kadena
    LRC = 257,    // Loopring
    QTUM = 258,   // Qtum
    CRV = 259,    // Curve DAO Token
    HT = 260,     // Huobi Token
    NEXO = 261,   // Nexo
    SUSHI = 262,  // SushiSwap
    KCS = 263,    // KuCoin Token
    BAT = 264,    // Basic Attention Token
    OKB = 265,    // OKB
    DCR = 266,    // Decred
    ICX = 267,    // ICON
    RVN = 268,    // Ravencoin
    SCRT = 269,   // Secret
    REV = 270,    // Revain
    AUDIO = 271,  // Audius
    ZIL = 272,    // Zilliqa
    TUSD = 273,   // TrueUSD
    YFI = 274,    // yearn.finance
    MINA = 275,   // Mina
    PERP = 276,   // Perpetual Protocol
    XDC = 277,    // XDC Network
    TEL = 278,    // Telcoin
    SNX = 279,    // Synthetix
    BTG = 280,    // Bitcoin Gold
    AFN = 281,    // Afghanistan Afghani
    ALL = 282,    // Albania Lek
    AMD = 283,    // Armenia Dram
    ANG = 284,    // Netherlands Antilles Guilder
    AOA = 285,    // Angola Kwanza
    ARS = 286,    // Argentina Peso
    AWG = 287,    // Aruba Guilder
    AZN = 288,    // Azerbaijan Manat
    BAM = 289,    // Bosnia and Herzegovina Convertible Mark
    BBD = 290,    // Barbados Dollar
    BDT = 291,    // Bangladesh Taka
    BGN = 292,    // Bulgaria Lev
    BHD = 293,    // Bahrain Dinar
    BIF = 294,    // Burundi Franc
    BMD = 295,    // Bermuda Dollar
    BND = 296,    // Brunei Darussalam Dollar
    BOB = 297,    // Bolivia Bolíviano
    BRL = 298,    // Brazil Real
    BSD = 299,    // Bahamas Dollar
    BTN = 300,    // Bhutan Ngultrum
    BWP = 301,    // Botswana Pula
    BYN = 302,    // Belarus Ruble
    BZD = 303,    // Belize Dollar
    CDF = 304,    // Congo/Kinshasa Franc
    CLP = 305,    // Chile Peso
    COP = 306,    // Colombia Peso
    CRC = 307,    // Costa Rica Colon
    CUC = 308,    // Cuba Convertible Peso
    CUP = 309,    // Cuba Peso
    CVE = 310,    // Cape Verde Escudo
    CZK = 311,    // Czech Republic Koruna
    DJF = 312,    // Djibouti Franc
    DKK = 313,    // Denmark Krone
    DOP = 314,    // Dominican Republic Peso
    DZD = 315,    // Algeria Dinar
    EGP = 316,    // Egypt Pound
    ERN = 317,    // Eritrea Nakfa
    ETB = 318,    // Ethiopia Birr
    FJD = 319,    // Fiji Dollar
    FKP = 320,    // Falkland Islands (Malvinas) Pound
    GEL = 321,    // Georgia Lari
    GGP = 322,    // Guernsey Pound
    GHS = 323,    // Ghana Cedi
    GIP = 324,    // Gibraltar Pound
    GMD = 325,    // Gambia Dalasi
    GNF = 326,    // Guinea Franc
    GTQ = 327,    // Guatemala Quetzal
    GYD = 328,    // Guyana Dollar
    HNL = 329,    // Honduras Lempira
    HRK = 330,    // Croatia Kuna
    HTG = 331,    // Haiti Gourde
    IDR = 332,    // Indonesia Rupiah
    ILS = 333,    // Israel Shekel
    IMP = 334,    // Isle of Man Pound
    IQD = 335,    // Iraq Dinar
    IRR = 336,    // Iran Rial
    ISK = 337,    // Iceland Krona
    JEP = 338,    // Jersey Pound
    JMD = 339,    // Jamaica Dollar
    JOD = 340,    // Jordan Dinar
    KES = 341,    // Kenya Shilling
    KGS = 342,    // Kyrgyzstan Som
    KHR = 343,    // Cambodia Riel
    KMF = 344,    // Comorian Franc
    KPW = 345,    // Korea (North) Won
    KRW = 346,    // Korea (South) Won
    KWD = 347,    // Kuwait Dinar
    KYD = 348,    // Cayman Islands Dollar
    KZT = 349,    // Kazakhstan Tenge
    LAK = 350,    // Laos Kip
    LBP = 351,    // Lebanon Pound
    LKR = 352,    // Sri Lanka Rupee
    LRD = 353,    // Liberia Dollar
    LSL = 354,    // Lesotho Loti
    LYD = 355,    // Libya Dinar
    MAD = 356,    // Morocco Dirham
    MDL = 357,    // Moldova Leu
    MGA = 358,    // Madagascar Ariary
    MKD = 359,    // Macedonia Denar
    MMK = 360,    // Myanmar (Burma) Kyat
    MNT = 361,    // Mongolia Tughrik
    MOP = 362,    // Macau Pataca
    MRU = 363,    // Mauritania Ouguiya
    MUR = 364,    // Mauritius Rupee
    MVR = 365,    // Maldives (Maldive Islands) Rufiyaa
    MWK = 366,    // Malawi Kwacha
    MZN = 367,    // Mozambique Metical
    NAD = 368,    // Namibia Dollar
    NGN = 369,    // Nigeria Naira
    NIO = 370,    // Nicaragua Cordoba
    NOK = 371,    // Norway Krone
    NPR = 372,    // Nepal Rupee
    OMR = 373,    // Oman Rial
    PAB = 374,    // Panama Balboa
    PEN = 375,    // Peru Sol
    PGK = 376,    // Papua New Guinea Kina
    PKR = 377,    // Pakistan Rupee
    PLN = 378,    // Poland Zloty
    PYG = 379,    // Paraguay Guarani
    QAR = 380,    // Qatar Riyal
    RON = 381,    // Romania Leu
    RSD = 382,    // Serbia Dinar
    RUB = 383,    // Russia Ruble
    RWF = 384,    // Rwanda Franc
    SAR = 385,    // Saudi Arabia Riyal
    SBD = 386,    // Solomon Islands Dollar
    SCR = 387,    // Seychelles Rupee
    SDG = 388,    // Sudan Pound
    SHP = 389,    // Saint Helena Pound
    SLL = 390,    // Sierra Leone Leone
    SOS = 391,    // Somalia Shilling
    SPL = 392,    // Seborga Luigino
    SRD = 393,    // Suriname Dollar
    STN = 394,    // São Tomé and Príncipe Dobra
    SVC = 395,    // El Salvador Colon
    SYP = 396,    // Syria Pound
    SZL = 397,    // eSwatini Lilangeni
    TJS = 398,    // Tajikistan Somoni
    TMT = 399,    // Turkmenistan Manat
    TND = 400,    // Tunisia Dinar
    TOP = 401,    // Tonga Pa'anga
    TRY = 402,    // Turkey Lira
    TTD = 403,    // Trinidad and Tobago Dollar
    TVD = 404,    // Tuvalu Dollar
    TWD = 405,    // Taiwan New Dollar
    TZS = 406,    // Tanzania Shilling
    UAH = 407,    // Ukraine Hryvnia
    UGX = 408,    // Uganda Shilling
    UYU = 409,    // Uruguay Peso
    UZS = 410,    // Uzbekistan Som
    VEF = 411,    // Venezuela Bolívar
    VND = 412,    // Viet Nam Dong
    VUV = 413,    // Vanuatu Vatu
    WST = 414,    // Samoa Tala
    XAF = 415,    // Communauté Financière Africaine (BEAC) CFA Franc BEAC
    XCD = 416,    // East Caribbean Dollar
    XDR = 417,    // International Monetary Fund (IMF) Special Drawing Rights
    XOF = 418,    // Communauté Financière Africaine (BCEAO) Franc
    XPF = 419,    // Comptoirs Français du Pacifique (CFP) Franc
    YER = 420,    // Yemen Rial
    ZMW = 421,    // Zambia Kwacha
    ZWD = 422,    // Zimbabwe Dollar
    Custom = 423,
};
}  // namespace opentxs::identity::wot::claim
